### ISSUE TITLE
How to train the model

### ISSUE THREAD

**Issue by NiteshMethani** [HMEIatJHU/SelectiveGeneration#1]
I have data but it is not in .pickle format. I have three directories "dev, test, train". So which directory I should convert to pickle?

Please upload the dataset. It becomes very hard to convert the downloaded dataset to align with the code.
Thanks.

**Comment by hongyuanmei** [comment]
Hi @NiteshMethani , sorry for the inconvenience. 
This version is still under-tested, and please use the code (and data files) that I shared on README. 
Thanks!
